### ISSUE TITLE
Functional improvement

### ISSUE THREAD

**Issue by KOZ39** [Electric1447/lcd-color-saturation#1]
Can you only make certain apps work like https://github.com/Kirezar/VitaGrafixConfigurator?

**Comment by Electric1447** [comment]
No as color_space_mode is for the entire system.

**Comment by KOZ39** [comment]
If so, can you add a registry recovery menu?

**Comment by KOZ39** [comment]
But thank you for your wonderful tools.

**Comment by Girotin** [comment]
Should close this one
