### ISSUE TITLE
[EXTRA FEATURE] Better colors with adrenaline at 2000 models

### ISSUE THREAD

**Issue by Girotin** [Electric1447/lcd-color-saturation#2]
In the Slim models, there's no option to turn on and off the color space that mimics the PSP one, and considering that without changing the registry, the regular colors are utilized on it, it's a little odd to play a PSP game, then go back to the LiveArea and get vivid colors again, not only that, but also, when we go back to a PSP game that way, sometimes is possible to see that it takes some seconds to change the color space and thanks to that shit, we see the game with greater colors for some time, then the colors get washed out again.

Seeing all this, I would like to ask an option to get the new color space working on Adrenaline too, I really like the better colors on the Vita games, and I've been wishing to play PSP with that colors after making this little mod :D

The main feature of this VPK it's just improving the colors in general, and that's what it already do, so I just marked my issue as an "extra feature", since the app it's already full-working, and this is not something essential.

**Comment by Girotin** [comment]
Really hoping for it to happen, it improves the colors a lot XD

**Comment by RinMaru** [comment]
looks like someone did this [LCD Colour Space Changer ](https://forum.devchroma.nl/index.php/topic,201.msg811.html)

**Comment by Girotin** [comment]
Yeah I saw it on reddit some time ago, I didn't remember that I opened an issue here about that lol
The plugin works perfectly well, I'll be closing this issue now, thanks for the reminder!
